export const CATEGORIES_ACTIONS = {
  SET_CATEGORIES: 'categories/SET_CATEGORIES',
  FETCH_CATEGORIES_PENDING: 'categories/FETCH_CATEGORIES_PENDING',
  FETCH_CATEGORIES_SUCCESS: 'categories/FETCH_CATEGORIES_SUCCESS',
  FETCH_CATEGORIES_REJECTED: 'categories/FETCH_CATEGORIES_REJECTED',
};
